### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by hdvvip** [atharva-naik/adbdjcaf#1]

**Comment by hdvvip** [comment]
![Selection_445](https://user-images.githubusercontent.com/42698038/125156834-8c66dd80-e135-11eb-8c53-68d8708e4aa7.png)
I see your co-author sriyash421 (Sriyash Poddar) posted scores on 07/05/2020. Maybe you guys should tell him to update the scores.

**Comment by atharva-naik** [comment]
Yes. Sorry for not replying earlier.
